permalink: pretty
relative_permalinks: true

# Setup
title: HAR Resources
tagline: A community curated list of resources, tools, projects and applications that support HTTP Archive (HAR)
baseurl: /har-resources

collections:
  applications:
    output: true

  articles:
    output: true

  browsers:
    output: true

  groups:
    output: true

  libraries:
    output: true

  services:
    output: true

  videos:
    output: true

markdown: redcarpet

# Custom vars
languages:
  csharp: "C#"
  java: Java
  js: JavaScript
  net: .Net
  objc: Objective-C
  perl: Perl
  php: PHP
  python: Python
  ruby: Ruby
